version: "3"
services:
  # FHIR Server
  sponsor-fhir-server:
    build: ../hapi-server
    container_name: sponsor-fhir-server
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://sponsor-postgres:5432/hapi"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
    ports:
      - "8082:8080"
  
  # Postgres for FHIR Server
  sponsor-postgres:
    image: postgres:15-alpine
    container_name: sponsor-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - sponsor-postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # Backend API
  sponsor-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sponsor-backend
    restart: on-failure
    environment:
      - FHIR_SERVER_URL=http://sponsor-fhir-server:8080/fhir
      - SPONSOR_SERVER_URL=http://sponsor-backend:8000
      - DATABASE_URL=sqlite:///./app.db
      - PYTHONUNBUFFERED=1  # Make Python output immediately visible in logs
    ports:
      - "8002:8000"
    depends_on:
      - sponsor-fhir-server
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Frontend
  sponsor-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sponsor-frontend
    restart: on-failure
    environment:
      - REACT_APP_API_URL=http://localhost:8002
      - REACT_APP_FHIR_SERVER_URL=http://localhost:8082/fhir
    ports:
      - "3000:3000"
    depends_on:
      - sponsor-backend

volumes:
  sponsor-postgres-data: